const Enum = require("enum");

const responseCodes = {
  CREATE_RECORD_SUCCESS: "CREATE_RECORD_SUCCESS",
  UPDATE_RECORD_SUCCESS: "UPDATE_RECORD_SUCCESS",
  DELETE_RECORD_SUCCESS: "DELETE_RECORD_SUCCESS",
  RETRIEVE_RECORD: "RETRIEVE_RECORD",
  RETRIEVE_RECORD_LIST: "RETRIEVE_RECORD_LIST",
  EMPTY_RECORD_LIST: "EMPTY_RECORD_LIST",
  VALIDATION_CREATE_FAILED: "VALIDATION_CREATE_FAILED",
  VALIDATION_UPDATE_FAILED: "VALIDATION_UPDATE_FAILED",
  CONTENT_NOT_FOUND: "CONTENT_NOT_FOUND",
  ERROR_PROCESSING: "ERROR_PROCESSING",
  DATA_PROCESSING_ERROR: "DATA_PROCESSING_ERROR",
  LOGIN_FIRST: "LOGIN_FIRST",
};

const validationCodes = {
  EMAIL_ALREADY_TAKEN: "Ang email ay nagamit na ng ibang account!",
  INVALID_PARAMETER: "INVALID_PARAMETER",
  MISSING_FIELDS: "MISSING_FIELDS",
  MISSING_FILES: "MISSING_FILES",
  RECORD_NOT_FOUND: "RECORD_NOT_FOUND",
  RECORD_ALREADY_EXISTS: "RECORD_ALREADY_EXISTS",
  PASSWORD_ALREADY_TAKEN: "Ang password ay nagamit na ng ibang account!",
  PASSWORD_SET: "PASSWORD_SET",
  LINK_WAS_SENT: "LINK_WAS_SENT",
  LINK_WAS_NOT_SENT: "LINK_WAS_NOT_SENT",
  REGISTRATION_SUCCESS: "REGISTRATION_SUCCESS",
  REGISTRATION_FAILED: "REGISTRATION_FAILED",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGIN_SUCCESSFUL: "LOGIN_SUCCESSFUL",
  LOGOUT_SUCCESSFUL: "LOGOUT_SUCCESSFUL",
  LOGOUT_FAILED: "LOGOUT_FAILED",
  INVALID_EMAIL: "Di wasto ang email!",
  INVALID_PASSWORD: "Di wasto ang password!",
  ACCOUNT_SUSPENDED:
    "Kasulukuyang nasuspende and iyong account maaaring kontakin ang administrator sa pamamagitan ng email!",
  CORRECT_OTP: "CORRECT_OTP",
  INVALID_OTP: "INVALID_OTP",
  ACCOUNT_NOT_ACTIVE:
    "Kasulukuyang di pa aktibo ang iyong account. Maghintay ng konpirmasyon galing sa administrator na ipapadala sayong email!",
  MESSAGE_SENT: "MESSAGE_SENT",
  MESSAGE_SENT_FAILED: "MESSAGE_SENT_FAILED",
};

const ResponseCodes = { ...responseCodes, ...validationCodes };

module.exports = ResponseCodes;
